language: scala
scala:
  - 2.11.6
jdk:
  - oraclejdk7
  - openjdk7
script: "cd core; sbt ++$TRAVIS_SCALA_VERSION test"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2b3a40366cf5905a1688
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

