
# custom variables defined here are accessible in the templates via {{ site.myvariable }}.

title: Axle Domain Specific Language
email: adam@axle-lang.org
description: > # this means to ignore newlines until "baseurl:"
  Axle Domain Specific Language
baseurl: ""
url: "http://axle-lang.org"
twitter_username: axlelang
github_username:  axlelang

include: [_tut]

# Build settings
markdown: kramdown
theme: minima
kramdown:
  input: GFM
